### ISSUE TITLE
As the production roll-out team, we want to document all the tasks associated with rolling out the new Open website, so that our launch day is as efficient as possible and website downtime is minimized.

### ISSUE THREAD

**Issue by dshaykewich** [BCcampus/open-sage#103]
**Conditions of Satisfaction**
1. Develop checklist of day-of go-live configurations and content edit requirements (after the code push to production) for launching the new Open site.  
Such as:
- new pages to build
- setting up parent/child relationships between pages
- page-specific content changes/additions
- page-specific 'customizer' content population
- page-specific feature image editing, uploading and setting

2. Discuss and assign responsibility of checklist items to team members and ensure they understand what must be done.

3. Determine how to leverage Github issues to validate "Done in Prod"

4. Other?

**Comment by paulagaube** [comment]
Kate and I were talking this morning and since all the new content pages are numbered, I think it would make sense on roll-out day to unpublish ALL web pages and then publish only those new pages we know are going to be live on Open. (The new pages will need to be renamed anyway.)

If we do this, then we won't run in to the problem of old content showing up on the site. We may run in to 404 errors, but we can test and debug before making the site live on launch day. 

One exception I know of: the "Contact" page on the new site likely won't need to change.
