### ISSUE TITLE
Add "Cambria College" to adoption form

### ISSUE THREAD

**Issue by josieg** [BCcampus/open-sage#219]
Hi Alex, 

Lauri would like to add "Cambria College" as one of the institutions listed on the "[Adoption form](https://open.bccampus.ca/adoption-of-an-open-textbook/)". I think there is something you have to do in the back end to make sure the stats are sorted/counted correctly before she can add the institution to the form? (See #209, which is related and might provide clarification.)

Would you be able to take care of this?

Thanks, 
Josie

**Comment by alex-418** [comment]
@josieg I've added this new institution to the form. You can safely add new institutions in the form, nothing to do on the back-end. (The reason we did that last time, was because an existing institution changed its name. So we edited the database to overwrite the old name with the new one... and the baseline where the name was updated in the code, is not in use.) 

![cambria](https://user-images.githubusercontent.com/17072191/72101592-e802a180-32d9-11ea-9ed4-0587ac032fbb.png)
